Compilation workaround for buggy wx 2.9
which causes gcc to barf "undefined reference to `non-virtual thunk" if wxTextCtrl gets derived from. 
This disables the custom context menu.
Looks like we can remove MuleTextCtrl entirely anyway.

See http://forum.amule.org/index.php?topic=18861